blank_issues_enabled: false
contact_links:
  - name: â“ Questions or General Help
    url: https://github.com/vijayshikhare/appdost-website/discussions
    about: Please ask questions here instead of opening an issue.
